/** 国家选项：每个国家使用本国语言（value: ISO 3166-1 alpha-2, label: 该国本地名称） */
export const COUNTRY_OPTIONS: { value: string; label: string }[] = [
  { value: 'AF', label: 'افغانستان' },
  { value: 'AX', label: 'Åland' },
  { value: 'AL', label: 'Shqipëria' },
  { value: 'DZ', label: 'الجزائر' },
  { value: 'AS', label: 'American Samoa' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AI', label: 'Anguilla' },
  { value: 'AG', label: 'Antigua and Barbuda' },
  { value: 'AM', label: 'Հայաստան' },
  { value: 'AW', label: 'Aruba' },
  { value: 'AU', label: 'Australia' },
  { value: 'BM', label: 'Bermuda' },
  { value: 'AT', label: 'Österreich' },
  { value: 'AZ', label: 'Azərbaycan' },
  { value: 'BS', label: 'Bahamas' },
  { value: 'BH', label: 'البحرين' },
  { value: 'BD', label: 'বাংলাদেশ' },
  { value: 'BB', label: 'Barbados' },
  { value: 'BY', label: 'Беларусь' },
  { value: 'BE', label: 'België' },
  { value: 'BZ', label: 'Belize' },
  { value: 'BJ', label: 'Bénin' },
  { value: 'BT', label: 'འབྲུག' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'BA', label: 'Bosna i Hercegovina' },
  { value: 'BW', label: 'Botswana' },
  { value: 'BR', label: 'Brasil' },
  { value: 'BN', label: 'Brunei' },
  { value: 'BG', label: 'България' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'KH', label: 'កម្ពុជា' },
  { value: 'CM', label: 'Cameroun' },
  { value: 'CA', label: 'Canada' },
  { value: 'CV', label: 'Cabo Verde' },
  { value: 'CF', label: 'République centrafricaine' },
  { value: 'TD', label: 'Tchad' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: '中国' },
  { value: 'CO', label: 'Colombia' },
  { value: 'CK', label: 'Cook Islands' },
  { value: 'CW', label: 'Curaçao' },
  { value: 'KM', label: 'Komori' },
  { value: 'CG', label: 'Congo' },
  { value: 'CD', label: 'Congo (RDC)' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'CI', label: "Côte d'Ivoire" },
  { value: 'HR', label: 'Hrvatska' },
  { value: 'CU', label: 'Cuba' },
  { value: 'CY', label: 'Κύπρος' },
  { value: 'CZ', label: 'Česko' },
  { value: 'DK', label: 'Danmark' },
  { value: 'DJ', label: 'جيبوتي' },
  { value: 'DM', label: 'Dominica' },
  { value: 'DO', label: 'República Dominicana' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'مصر' },
  { value: 'EH', label: 'الصحراء الغربية' },
  { value: 'FK', label: 'Falkland Islands' },
  { value: 'FO', label: 'Føroyar' },
  { value: 'GF', label: 'Guyane française' },
  { value: 'GG', label: 'Guernsey' },
  { value: 'GI', label: 'Gibraltar' },
  { value: 'GL', label: 'Kalaallit Nunaat' },
  { value: 'GP', label: 'Guadeloupe' },
  { value: 'GU', label: 'Guåhan' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'GQ', label: 'Guinea Ecuatorial' },
  { value: 'ER', label: 'ኤርትራ' },
  { value: 'EE', label: 'Eesti' },
  { value: 'SZ', label: 'eSwatini' },
  { value: 'ET', label: 'ኢትዮጵያ' },
  { value: 'FJ', label: 'Fiji' },
  { value: 'FI', label: 'Suomi' },
  { value: 'FR', label: 'France' },
  { value: 'GA', label: 'Gabon' },
  { value: 'GM', label: 'Gambia' },
  { value: 'GE', label: 'საქართველო' },
  { value: 'DE', label: 'Deutschland' },
  { value: 'GH', label: 'Ghana' },
  { value: 'GR', label: 'Ελλάδα' },
  { value: 'GD', label: 'Grenada' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GN', label: 'Guinée' },
  { value: 'GW', label: 'Guiné-Bissau' },
  { value: 'GY', label: 'Guyana' },
  { value: 'HT', label: 'Haïti' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HK', label: '香港' },
  { value: 'HU', label: 'Magyarország' },
  { value: 'IM', label: 'Isle of Man' },
  { value: 'IS', label: 'Ísland' },
  { value: 'IN', label: 'भारत' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IR', label: 'ایران' },
  { value: 'IQ', label: 'العراق' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IL', label: 'ישראל' },
  { value: 'IT', label: 'Italia' },
  { value: 'JM', label: 'Jamaica' },
  { value: 'JP', label: '日本' },
  { value: 'JO', label: 'الأردن' },
  { value: 'JE', label: 'Jersey' },
  { value: 'KZ', label: 'Қазақстан' },
  { value: 'XK', label: 'Kosova' },
  { value: 'KY', label: 'Cayman Islands' },
  { value: 'KE', label: 'Kenya' },
  { value: 'KI', label: 'Kiribati' },
  { value: 'KW', label: 'الكويت' },
  { value: 'KG', label: 'Кыргызстан' },
  { value: 'LA', label: 'ລາວ' },
  { value: 'LV', label: 'Latvija' },
  { value: 'LB', label: 'لبنان' },
  { value: 'LS', label: 'Lesotho' },
  { value: 'LR', label: 'Liberia' },
  { value: 'LY', label: 'ليبيا' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lietuva' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MO', label: '澳門' },
  { value: 'MG', label: 'Madagasikara' },
  { value: 'MW', label: 'Malawi' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'MV', label: 'ދިވެހިރާއްޖެ' },
  { value: 'ML', label: 'Mali' },
  { value: 'MT', label: 'Malta' },
  { value: 'MH', label: 'Marshall Islands' },
  { value: 'MR', label: 'موريتانيا' },
  { value: 'MU', label: 'Maurice' },
  { value: 'MX', label: 'México' },
  { value: 'FM', label: 'Micronesia' },
  { value: 'MD', label: 'Moldova' },
  { value: 'MC', label: 'Monaco' },
  { value: 'MN', label: 'Монгол' },
  { value: 'ME', label: 'Crna Gora' },
  { value: 'MA', label: 'المغرب' },
  { value: 'MQ', label: 'Martinique' },
  { value: 'MZ', label: 'Moçambique' },
  { value: 'MM', label: 'မြန်မာ' },
  { value: 'MS', label: 'Montserrat' },
  { value: 'NA', label: 'Namibia' },
  { value: 'NC', label: 'Nouvelle-Calédonie' },
  { value: 'NU', label: 'Niue' },
  { value: 'MP', label: 'Northern Mariana Islands' },
  { value: 'NR', label: 'Nauru' },
  { value: 'NP', label: 'नेपाल' },
  { value: 'NL', label: 'Nederland' },
  { value: 'NZ', label: 'Aotearoa' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'NE', label: 'Niger' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'KP', label: '조선' },
  { value: 'KR', label: '한국' },
  { value: 'MK', label: 'Северна Македонија' },
  { value: 'NO', label: 'Norge' },
  { value: 'OM', label: 'عُمان' },
  { value: 'PK', label: 'پاکستان' },
  { value: 'PW', label: 'Palau' },
  { value: 'PS', label: 'فلسطين' },
  { value: 'PA', label: 'Panamá' },
  { value: 'PG', label: 'Papua New Guinea' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'PE', label: 'Perú' },
  { value: 'PH', label: 'Pilipinas' },
  { value: 'PF', label: 'Polynésie française' },
  { value: 'PL', label: 'Polska' },
  { value: 'PT', label: 'Portugal' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'QA', label: 'قطر' },
  { value: 'RE', label: 'La Réunion' },
  { value: 'RO', label: 'România' },
  { value: 'RU', label: 'Россия' },
  { value: 'RW', label: "u Rwanda" },
  { value: 'KN', label: 'Saint Kitts and Nevis' },
  { value: 'LC', label: 'Saint Lucia' },
  { value: 'VC', label: 'Saint Vincent and the Grenadines' },
  { value: 'WS', label: 'Samoa' },
  { value: 'SM', label: 'San Marino' },
  { value: 'ST', label: 'São Tomé e Príncipe' },
  { value: 'SA', label: 'السعودية' },
  { value: 'SN', label: 'Sénégal' },
  { value: 'RS', label: 'Србија' },
  { value: 'SC', label: 'Seychelles' },
  { value: 'SL', label: 'Sierra Leone' },
  { value: 'SG', label: '新加坡' },
  { value: 'SX', label: 'Sint Maarten' },
  { value: 'SK', label: 'Slovensko' },
  { value: 'SI', label: 'Slovenija' },
  { value: 'SB', label: 'Solomon Islands' },
  { value: 'SO', label: 'Soomaaliya' },
  { value: 'ZA', label: 'Suid-Afrika' },
  { value: 'SS', label: 'South Sudan' },
  { value: 'ES', label: 'España' },
  { value: 'LK', label: 'ශ්‍රී ලංකා' },
  { value: 'SD', label: 'السودان' },
  { value: 'SR', label: 'Suriname' },
  { value: 'SE', label: 'Sverige' },
  { value: 'CH', label: 'Schweiz' },
  { value: 'SY', label: 'سوريا' },
  { value: 'TW', label: '台灣' },
  { value: 'TJ', label: 'Тоҷикистон' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'TH', label: 'ไทย' },
  { value: 'TL', label: 'Timor-Leste' },
  { value: 'TG', label: 'Togo' },
  { value: 'TK', label: 'Tokelau' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinidad and Tobago' },
  { value: 'TN', label: 'تونس' },
  { value: 'TR', label: 'Türkiye' },
  { value: 'TM', label: 'Türkmenistan' },
  { value: 'TC', label: 'Turks and Caicos Islands' },
  { value: 'TV', label: 'Tuvalu' },
  { value: 'UG', label: 'Uganda' },
  { value: 'UA', label: 'Україна' },
  { value: 'AE', label: 'الإمارات' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'US', label: 'United States' },
  { value: 'VI', label: 'U.S. Virgin Islands' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'UZ', label: 'Oʻzbekiston' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VA', label: 'Vaticano' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Việt Nam' },
  { value: 'VG', label: 'British Virgin Islands' },
  { value: 'WF', label: 'Wallis-et-Futuna' },
  { value: 'YE', label: 'اليمن' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'ZW', label: 'Zimbabwe' },
]
